# Project Sentinel — reproducibility entrypoints
# Every number in report/metrics.json is regenerated by `make reproduce`.

DATA_DIR ?= /Users/ritigya/Downloads/ieee-fraud-detection
PY := .venv/bin/python
PIP := .venv/bin/pip

.PHONY: venv splits baseline reproduce clean

venv:
	python3 -m venv .venv
	$(PIP) install -U pip
	$(PIP) install -r requirements.txt

# Temporal 70/15/15 split of train_transaction.csv (+ identity join). Never shuffled.
splits:
	SENTINEL_DATA_DIR=$(DATA_DIR) $(PY) data/prepare_splits.py

# LightGBM on raw features only (no ring features yet). Held-out test touched once.
baseline:
	$(PY) train/baseline.py

reproduce: splits baseline
	@echo ""
	@echo "Done -> report/metrics.json"

clean:
	rm -rf data/splits report/metrics.json report/figures
